<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Pages Language Lines
    |--------------------------------------------------------------------------
    */
    'form' => [
        'email_from' => 'Email From',
        'email_to' => 'Email To',
        'email_submit' => 'Submit Page',
        'template' => 'Form Template',
        'captcha' => 'Enable Secure Captcha',
        'submissions' => 'Form Submissions',
    ],
    'gallery' => [
        'num_pictures' => 'No of Pictures',
        'edit_button' => 'Edit Gallery'
    ],
    'image' => [
        'source' => 'Image Source',
        'button' => 'Select Image',
        'title' => 'Image Title',
        'no_image' => 'No Image',
    ],
    'link' => [
        'or' => 'or',
        'button' => 'Select Doc',
    ],
    'repeater' => [
        'button_add' => 'Add Another',
        'button_default' => 'Repeater Block',
    ],
    'selectuser' => [
        'placeholder' => 'Or Add Custom Author'
    ],
    'video' => [
        'clear' => 'Clear selection',
        'results' => 'Results are generated by YouTubes search system.',
    ],
    'videouploaded' => [
        'button' => 'Select video',
        'info' => 'Please upload the 3 video files with same name (.mp4, .webm, .ogv)'
    ],
    'selectuserlevel' => [
        'default_option' => 'None',
        'error' => 'User level error'
    ],
    'map' => [
        'long' => 'Longitude',
        'lat' => 'Latitude'
    ],

];
